### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by macign** [mayajs/router#2]
# ROADMAP
This objectives are subject to changes and will be updated frequently. If you have suggestion feel free to contribute.

## Router Module
- ### init
  - [x] Use as a replacement for the anonymous `function() => {}` when creating `http.createServer`
  - [x] Build `request` and `response` handlers that will be pass on the selected route
  - [x] Create `interface` for request and response handlers
  - [x] Parse incoming `request url`
  - [x] Get `query string, headers and method` from the parsed url string
  - [x] Build `data from chunks` in request `data` event listener
  - [x] Add `send()` method in `response handler`
  - [x] Call selected route in request `end` event listener

>NOTE: This library is not responsible for parsing `req.body`.

- ### add() method
  - [x] Create a `routes` object that will handle all kinds of http methods
  - [x] Create interface for `http methods`
  - [x] Create interface for `routes` and individual `route`
    - A route must have a `path` and a `callback` function
  - [x] Map object route to be added on the routes object

>NOTE: This **add()** function can be called multiple times before calling the **init**. This way we can register multiple routes before any request happen.

- ### error() method
  - [x] This function will be called when there is no routes found
  - [x] Accepts an anonymous `function() => {}`

> **NOTE:** If this function is not called our router will log an error and the server will continue running.

## Request Params
- [x] Able to parse `params` variable in req.url string i.e. `/:id`

## TEST
- [ ] Use ts-jest for unit testing
- [ ] Add coverage
- [ ] Run test on CI tools or Github Actions

## Other Features
- [x] `Middleware` functions like `express`  #6 
- [x] `Method chaining` for ease of use #4 
- [x] Defining routes using `constructor`
- [x] Defining `children routes`
- [x] `Validation` of routes`?`
- [x] `Next` function`?` #6 

## Documentation
>NOTE: I don't have any talent on this part.

### NOTE: This are basic functionalities and not final. If you want to add more features we are open for collaboration.

**Comment by macign** [comment]
Close #16
