### ISSUE TITLE
🚀 FEAT: Handling of middlewares

### ISSUE THREAD

**Issue by Mackignacio** [mayajs/router#5]
## 📝 Description

Most of the routing library can handle middlewares. But in our case we will handle two types of middlewares. One for our own and one for ExpressJS like middlewares.

## ⚙️ Component
- middleware.ts

## 📋 Todo:

- [x] Create a middleware class
- [x] Handle both @mayajs/router and Express like middlewares
- [x] Handle async middleware
- [x] Able to pass custom interface when creating a middleware
- [x] Dispatch middlewares before initializing all the routes

## 🔍 Additional Info
Convert  body_parser to a middleware after this.
