### ISSUE TITLE
🚀 FEAT: Body Parser as middleware

### ISSUE THREAD

**Issue by Mackignacio** [mayajs/router#8]
## 📝 Description

The implementation of our built it body parse is fine. The addition of middleware function makes our body parser act like a middleware and can be replaced by other library that do the same thing. For this we will update our implementation for it and convert it as a middleware.

## ⚙️ Component
- body_parser.ts

## 📋 Todo:

- [ ] Change implementation of body parser to middleware
- [ ] Adds body parser on the middleware array
- [ ] Add body parser before all the middleware are added to prevent conflict from other middleware
